# Generated by Django 5.2.6 on 2025-10-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('prescription_text', models.TextField(blank=True, help_text='Enter prescription details if no file is uploaded')),
                ('prescribed_by', models.CharField(blank=True, max_length=100)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.customer')),
            ],
        ),
    ]
